feat: implement select base token page
BlockheaderWeb3-Community/autoswappr-dapp pull request #14
Opened 2024-11-22 18:19 UTC by Tonyverse-ops

## Description
feat: implement select base token page

## Related Issue(s)
#3 

- [x] Read the [contributing docs](../CONTRIBUTING.md) (if this is your first contribution)
- [x] Verified this is not a duplicate of any existing pull request

- [x] Performed a self-review of the code
- [x] Linked the issues which this PR resolves
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Documented the changes in code (API docs will be generated automatically)

2024-11-25 12:34 UTC, Oshioke-Salaki commented
sync your fork and update your pr. The layout background on the layout has been changed.

2024-11-26 14:18 UTC, Tonyverse-ops commented
@Oshioke-Salaki kindly review and merge :)

2024-11-26 14:37 UTC, Oshioke-Salaki commented
please create a select-base-token route so i can be able to preview your component.

2024-11-26 15:09 UTC, Oshioke-Salaki commented
Please make it responsive

2024-11-26 23:26 UTC, Tonyverse-ops commented
@Oshioke-Salaki implemented required change

2024-11-27 08:57 UTC, Oshioke-Salaki commented
Build is failing

2024-11-27 12:39 UTC, Tonyverse-ops commented
hey @Oshioke-Salaki kindly review :)

2024-11-27 14:14 UTC, Oshioke-Salaki requested changes

2024-11-27 14:14 UTC, Oshioke-Salaki commented on app/components/select-base-token.tsx
> +    <div className="flex justify-center items-center mt-10 w-full px-4 bg-gradient-to-b from-[#08001F] to-[#040010]">
No need for this gradient.

2024-11-27 14:14 UTC, Oshioke-Salaki commented on app/components/select-base-token.tsx
> +      <div className="flex relative justify-center items-center rounded-3xl border border-[#170F2E] text-center w-full max-w-[50rem] flex-col bg-[#08001F]/90 backdrop-blur-sm p-6 mx-4">
`bg-[#08001F]/90 backdrop-blur-sm' no need for this

2024-11-27 14:14 UTC, Oshioke-Salaki commented
Please sync your fork and update your pr.

2024-11-27 14:15 UTC, Oshioke-Salaki commented
Also noticed that your page doesn't take up the full page of the screen. Please fix that.
<img width="760" alt="Screenshot 2024-11-27 at 15 15 20" src="https://github.com/user-attachments/assets/7a494e44-b88a-427b-ba99-4e73af733291">

2024-11-27 15:50 UTC, Tonyverse-ops commented
hey @Oshioke-Salaki kindly review :)

2024-11-27 15:54 UTC, Oshioke-Salaki commented
The background isn't visible on mobile screens and tablets.

2024-11-27 15:57 UTC, Oshioke-Salaki commented
<img width="760" alt="Screenshot 2024-11-27 at 16 56 22" src="https://github.com/user-attachments/assets/8f77a626-0d7c-45f7-b515-9f25a088bf30">
Please add some space between the component and the header on mobile screens. Also the close button and the text are overlapping.

2024-11-27 16:43 UTC, Tonyverse-ops commented
@Oshioke-Salaki kindly review 
@Oshioke-Salaki

2024-11-27 18:44 UTC, Oshioke-Salaki commented
lgtm 🚀

2024-11-27 18:44 UTC, merged