feat: Dex history page
BlockheaderWeb3-Community/autoswappr-dapp pull request #20
Opened 2024-11-27 21:31 UTC by Yunusabdul38

## Description

_Detailed description of proposed changes_

## Related Issue(s)

Closes #9
## Checklist:

- [x] Read the [contributing docs](../CONTRIBUTING.md) (if this is your first contribution)
- [x] Verified this is not a duplicate of any existing pull request

- [x] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Linked the issues which this PR resolves
- [x] Documented the changes in code (API docs will be generated automatically)

2024-11-28 08:55 UTC, Yunusabdul38 commented
@Oshioke-Salaki pls review

2024-11-28 09:07 UTC, Oshioke-Salaki requested changes

2024-11-28 09:07 UTC, Oshioke-Salaki commented on app/history/page.tsx
This doesn't take up the full height of the display screen.
<img width="1680" alt="Screenshot 2024-11-28 at 10 07 07" src="https://github.com/user-attachments/assets/764c889e-3850-4442-a39c-ef1d33a58eac">

2024-11-28 10:27 UTC, Oshioke-Salaki requested changes

2024-11-28 10:27 UTC, Oshioke-Salaki commented on app/history/page.tsx
<img width="1088" alt="Screenshot 2024-11-28 at 11 25 18" src="https://github.com/user-attachments/assets/43db487c-aa53-4e43-adff-7faf460bd6b6">
Align the items in the `to` column to the left

2024-11-28 10:27 UTC, Oshioke-Salaki commented on app/history/page.tsx
> +import btc from "../../public/coin-logos/btc-logo.png"
snyc your fork and make use of the svg versions of the coins. If a particular svg coin is not available in the repo, you can go ahead and export it from the figma file and make use of it.

2024-11-28 12:34 UTC, Yunusabdul38 commented
@Oshioke-Salaki pls review

2024-11-29 22:55 UTC, Oshioke-Salaki commented
lgtm 🚀

2024-11-29 22:55 UTC, merged