fix(footer-#49): display dynamic date, ensure all link are functional
BlockheaderWeb3-Community/autoswappr-dapp pull request #58
Opened 2024-12-13 21:15 UTC by portableDD

## Description

_Detailed description of proposed changes_

## Related Issue(s)

Closes #
## Checklist:

- [ ] Read the [contributing docs](../CONTRIBUTING.md) (if this is your first contribution)
- [ ] Verified this is not a duplicate of any existing pull request

- [ ] Performed a self-review of the code
- [ ] Rebased to the last commit of the target branch (or merged it into my branch)
- [ ] Linked the issues which this PR resolves
- [ ] Documented the changes in code (API docs will be generated automatically)

2024-12-13 21:26 UTC, portableDD commented
Please review @Abeeujah

2024-12-16 08:57 UTC, princeibs requested changes
Hi @portableDD, can you fix issue causing build to fail?

2024-12-16 09:38 UTC, portableDD commented
@princeibs the issues has been fixed

2024-12-16 18:02 UTC, princeibs requested changes

2024-12-16 18:02 UTC, princeibs commented on app/components/Footer.ts
Please add the correct links.

Twitter: `https://twitter.com/auto_swappr`
Telegram: `https://t.co/yFNm0juRkX`
Github: `https://github.com/BlockheaderWeb3-Community/autoswappr-dapp`
Documentation: `/documentation`

2024-12-17 11:55 UTC, Utilitycoder approved these changes

2024-12-17 11:56 UTC, merged