Merge pull request #32 from Olexandr88/patch-1
BlockheaderWeb3-Community/autoswappr-dapp pull request #60
Opened 2024-12-14 03:09 UTC by Xaxxoo

docs: readme

## Description

_Detailed description of proposed changes_

## Related Issue(s)

Closes #
## Checklist:

- [ ] Read the [contributing docs](../CONTRIBUTING.md) (if this is your first contribution)
- [ ] Verified this is not a duplicate of any existing pull request

- [ ] Performed a self-review of the code
- [ ] Rebased to the last commit of the target branch (or merged it into my branch)
- [ ] Linked the issues which this PR resolves
- [ ] Documented the changes in code (API docs will be generated automatically)

2024-12-16 19:31 UTC, Abeeujah requested changes

2024-12-16 19:31 UTC, Abeeujah commented on app/components/footer.tsx
>        {/* Copyright section */}
Hi @Xaxxoo you shouldn't be modifying this component if I'm correct.

2024-12-16 19:31 UTC, Abeeujah commented on app/components/footer.tsx
>          <Image
Neither should you be doing this.

2024-12-16 19:31 UTC, Abeeujah commented on app/components/swapper.tsx
> +
This is not the intended functionality you were to implement, you were supposed to make sure that when the swap button is clicked, an unstable token doesn't end up in the stable token's placeholder.

2024-12-16 19:31 UTC, Abeeujah commented on app/components/swapper.tsx
> +
You wasn't supposed to change the position of the swap button.

2024-12-21 08:49 UTC, princeibs commented
#64

2024-12-21 08:49 UTC, closed without merging